spm:
  - url: 
    from:
    path: 
    branch:
    exact: 
    revision:
    search-paths: []
    linked-libs: []

search-paths: []
linked-libs: []

ios:
  name: SimplyE
  id: com.scade.simplye
  device-family: iphone # iphone, ipad or universal
  supported-interface-orientations: ['portrait'] # portrait, upside_down, landscape_left or landscape_right
  supported-interface-orientationsiPad: ['portrait']
  entitlements-file: 
  app-delegate-file:
  simulator:
    os: 12.1
    output: SimplyE/.build/ios-simulator
    extra-args:
    search-paths: []
    linked-libs: []
  device: 
    os: 12.1
    output: SimplyE/.build/ios-device
    product-path: SimplyE/Product/ios-device
    extra-args: 
    search-paths: []
    linked-libs: []
  mac:
    os: 10.11
    output: SimplyE/.build/scade-simulator
    extra-args: 
    search-paths: []
    linked-libs: []
  sign:
    provision-profile:
    certificate:
    beta-reports-active: false
  icons: 
    iphone: # or ipad, sizes: 20X20, 29X29, 40X40, 60X60, 76X76, 83.5X83.5
      60X60_2X: Assets/ScadeBooksIcons/ios/AppIcon.appiconset/Icon-App-60x60@2x.png
      76X76_2X: Assets/ScadeBooksIcons/ios/AppIcon.appiconset/Icon-App-76x76@2x.png
      76X76_3X: Assets/ScadeBooksIcons/ios/AppIcon.appiconset/Icon-App-76x76@3x.png
      83.5X83.5_2X: Assets/ScadeBooksIcons/ios/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
    marketing:
      1024X1024_1X: Assets/ScadeBooksIcons/ios/iTunesArtwork@1x.png
  plist: 
    - key: CFBundleShortVersionString
      type: string  # string, bool, int, list or dict
      value: 1.0
    - key: CFBundleVersion
      type: string
      value: 1
    - key: NSLocationWhenInUseUsageDescription
      type: string
      value: 
    - key: NSCameraUsageDescription
      type: string
      value: Take pictures from camera
    - key: NSPhotoLibraryUsageDescription
      type: string
      value: Choose a photo from your library

android:
  name: simplye
  id: com.scade.simplye
  version-name: 1.0.0
  version-code: 1
  build-type: Release
  key-store-properties: /Users/olanrewajuolakunle/keystore.properties
  google-api-key: 
  manifest-file:
  permissions: []
  armeabi-v7a:
    output: SimplyE/.build/android-armeabi-v7a
    product-path: SimplyE/Product/android-armeabi-v7a
    extra-args:
    search-paths: []
    linked-libs: []
  arm64-v8a:
    output: SimplyE/.build/android-arm64-v8a
    product-path: SimplyE/Product/android-arm64-v8a
    extra-args:
    search-paths: []
    linked-libs: []
  x86:
    output: SimplyE/.build/android-x86
    product-path: SimplyE/Product/android-x86
    extra-args:
    search-paths: []
    linked-libs: []
  x86_64:
    output: SimplyE/.build/android-x86_64
    product-path: SimplyE/Product/android-x86_64
    extra-args:
    search-paths: []
    linked-libs: []
  intent-filters:
    - action:
      scheme:
      categories: [] 
  icons:
    mdpi: Assets/ScadeBooksIcons/android/mipmap-mdpi/ic_launcher.png
    hdpi: Assets/ScadeBooksIcons/android/mipmap-hdpi/ic_launcher.png
    xhdpi: Assets/ScadeBooksIcons/android/mipmap-xhdpi/ic_launcher.png
    xxhdpi: Assets/ScadeBooksIcons/android/mipmap-xxhdpi/ic_launcher.png